## Data Assessment of Waterflow Historical Data

**Metadata Summary**  
- üìÖ **Date of Retrieval:** JULY 1, 2025  
- üåê **Source of Data:** LGU San Jacinto Treasury Records
- üìÑ **License/Permission:**  
- üßë‚Äçüíº **Prepared by:** MARK JUNE E. ALMOJUELA

This notebook is used to split the compiled records with more than one month in one file to create chunks of records for each month.

In [65]:
# Initialization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

Split MAR_APR2020 record to create MAR2020 and APR2020

In [66]:
# Initialize df as None at the start
df = None

# Define the file path
file_path = os.path.normpath("../../dataset/raw/2020/MAR_APR2020.csv")

# Print the full path for verification
print(f"Attempting to load file from: {os.path.abspath(file_path)}")

try:
    if not os.path.exists(file_path):
        print("Error: File not found at the specified location.")
        dir_path = os.path.dirname(file_path)
        if not os.path.exists(dir_path):
            print(f"Error: Directory not found: {os.path.abspath(dir_path)}")
        else:
            print("Files in directory:")
            print(os.listdir(dir_path))
    else:
        # Try UTF-8 encoding first
        try:
            df = pd.read_csv(file_path)
            print("File loaded successfully with UTF-8 encoding!")
        except UnicodeDecodeError:
            print("Trying with 'latin1' encoding...")
            df = pd.read_csv(file_path, encoding='latin1')
            print("File loaded successfully with 'latin1' encoding!")
        
        # Display info if df was loaded
        if df is not None:
            print(f"\nNumber of rows: {len(df)}")
            print("\nFirst few rows:")
            print(df.head())
            print("\nColumns in the dataset:")
            print(df.columns.tolist())
            
except Exception as e:
    print(f"An error occurred: {e}")

# The df variable is now available for use in subsequent cells

Attempting to load file from: c:\Users\Mark June Almojuela\OneDrive - Bicol University\WaterFlow\AI\Model Training\dataset\raw\2020\MAR_APR2020.csv
Trying with 'latin1' encoding...
File loaded successfully with 'latin1' encoding!

Number of rows: 1633

First few rows:
   Control Number      Consumer's Name       Address Water Meter Serial #  \
0        501549.0       Alba√±o, Lilane  Alicante St.                  NaN
1        500750.0  Aljecera, Marcelino  Alicante St.                  NaN
2        500990.0       Almi√±ana, Irus  Alicante St.                  NaN
3        500505.0       Almi√±e, Edison  Alicante St.             95022096
4        501542.0       Almi√±e, Filben  Alicante St.                  NaN

  Previous Present  Cons.    Amount
0      218     247   29.0    87.00
1     3030    3051   21.0    63.00
2      471     537   66.0   198.00
3        2      63   61.0   183.00
4     3271    3314   43.0   129.00

Columns in the dataset:
['Control Number', "Consumer's Name", 'Address', 'Water Meter Serial #', 'Previous', 'Present', 'Cons.', 'Amount']

In [67]:
# Count of null/NaN values in each column
null_counts = df.isnull().sum()
print("Count of null/NaN values per column:")
print(null_counts[null_counts > 0])  # Only show columns with null values

# Count of rows with any null/NaN values
rows_with_nulls = df[df.isnull().any(axis=1)]
print(f"\nNumber of rows with any null/NaN values: {len(rows_with_nulls)}")

Count of null/NaN values per column:
Control Number            1
Water Meter Serial #    698
Previous                201
Present                 403
Cons.                   548
Amount                  416
dtype: int64

Number of rows with any null/NaN values: 1026

Creating MAR2020 AND APR2020 records

In [68]:
# Logic test for MAR_APR2020.csv record split
for index, row in df.iterrows():
    try:
        control_number = row["Control Number"]
        consumer_name = row["Consumer's Name"]
        address = row["Address"]
        serial_number = row["Water Meter Serial #"]
        try:
            previous_reading = int(row["Previous"])
        except ValueError:
            previous_reading = 0
        
        try:
            present_reading = int(row["Present"])
        except ValueError:
            if previous_reading > 0:
                present_reading = previous_reading
            else:
                present_reading = 0
        
        current_reading = present_reading - ((present_reading - previous_reading) / 2)
        
        total_consumption = present_reading - previous_reading
        total_amount = total_consumption * 10

        print(control_number, consumer_name, address, serial_number, 
              previous_reading, current_reading, total_consumption, total_amount)
              
    except Exception as e:
        print(f"Error processing row {index}: {e}")

501549.0 Alba√±o, Lilane Alicante St. nan 218 232.5 29 290
500750.0 Aljecera, Marcelino Alicante St. nan 3030 3040.5 21 210
500990.0 Almi√±ana, Irus Alicante St. nan 471 504.0 66 660
500505.0 Almi√±e, Edison Alicante St. 95022096 2 32.5 61 610
501542.0 Almi√±e, Filben Alicante St. nan 3271 3292.5 43 430
500431.0 Almi√±e, Franchie Alicante St. 121006093 0 0.0 0 0
500263.0 Almodal, Arna Alicante St. 9588526 5228 5240.5 25 250
501240.0 Almocera, Owen Alicante St. nan 67 102.5 71 710
500484.0 Almodal, Erlinda Alicante St. 028086-02 0 0.0 0 0
500739.0 Almodal, Jolly Alicante St. 017902-02 1795 1861.5 133 1330
500544.0 Almodal, Noe Alicante St. nan 2418 2418.0 0 0
500187.0 Almodiel, Arles Alicante St. 9074313 3210 3210.0 0 0
501447.0 Almodiel, Mary Grace Alicante St. nan 238 240.5 5 50
501453.0 Alcantara, Hilda Alicante St. nan 183 189.5 13 130
501317.0 Almoete, Ike Alicante St. nan 595 603.0 16 160
501280.0 Almojuela, Arlic Alicante St. nan 424 448.0 48 480
500248.0 Almojuela, Rogelio Alicante St. 956320 6706 6745.0 78 780
501028.0 Almoradie, Marites Alicante St. nan 1914 1923.5 19 190
501437.0 Almoradie, Geann Alicante St. nan 1386 1437.0 102 1020
500433.0 Almoradie, Marina Alicante St. nan 340 369.0 58 580
500260.0 Altiche, Antonio Alicante St. nan 0 0.0 0 0
501663.0 Altiche, Nenita Alicante St. nan 56 56.0 0 0
500185.0 Aspa, Leny Alicante St. 245534 1518 1522.5 9 90
500169.0 A√±onuevo, Paz Alicante St. 027568-02 3162 3162.0 0 0
501232.0 Anabe, Antonio Alicante St. 08-82569 0 0.0 0 0
500479.0 Azares, Jeffrey Alicante St. 028462-02 64 82.5 37 370
500009.0 Barruga, Expedito Alicante St. 017766-02 2014 2023.5 19 190
500472.0 Barruga, Loreto Alicante St. 028652-02 814 849.0 70 700
501393.0 Barrun, Ana Alicante St. 028576-02 602 623.0 42 420
500094.0 Barrun, Divina Alicante St. 954950 2703 2722.0 38 380
501020.0 Barrun, Emilio Alicante St. nan 1995 2012.5 35 350
500692.0 Barrun, Jose Alicante St. nan 0 0.0 0 0
500585.0 Barrun, Nida Alicante St. nan 321 346.5 51 510
500330.0 Barrun, Vito Alicante St. 151228 0 16.0 32 320
501260.0 Barsaga, Natividad Alicante St. 11075846 130 172.0 84 840
501330.0 Barsaga, Natividad 2 Alicante St. nan 66 66.0 0 0
501167.0 Bartolabac, Renato Alicante St. nan 1273 1287.5 29 290
500740.0 Bartolata, Jose Alicante St. 017903-02 0 0.0 0 0
500278.0 Bartolay, Felipe Alicante St. 028463-02 1878 1891.5 27 270
500861.0 Bartolata, Lourdes Alicante St. 957925 2189 2201.5 25 250
501021.0 Bartolay, Isaias Alicante St. nan 0 0.0 0 0
500254.0 Bartolay, Nilda Alicante St. 028194-02 1804 1805.0 2 20
501301.0 Bartolay, Nilo Alicante St. nan 910 920.5 21 210
501048.0 Bartolay, Nolyn Alicante St. nan 496 531.5 71 710
500095.0 Bartolay, Rustom Alicante St. 9521569 1322 1332.0 20 200
501176.0 Bartolay, Marites Alicante St. 10092103 0 858.0 1716 17160
500045.0 Bartolay, Orlando Alicante St. nan 0 0.0 0 0
500405.0 Bartolay, Orlando Alicante St. nan 1571 1578.0 14 140
500380.0 Borejon, Melchor Alicante St. 20048213 1064 1071.0 14 140
501329.0 Borejon, Noli Alicante St. nan 238 256.5 37 370
500377.0 Borromeo, Elisa Alicante St. 9665024 234 247.0 26 260
501522.0 Borromeo, Gener Alicante St. nan 166 174.0 16 160
500251.0 Cabiles, Nicanor Alicante St. 970701083 904 942.0 76 760
500014.0 Canchela, Emma Alicante St. 954415 3713 3725.5 25 250
500262.0 Canchela, Isaias Alicante St. 952564 2700 2713.0 26 260
501676.0 Cantoria, Jose Alicante St. nan 18 30.5 25 250
500696.0 Cantoria, Lourdes Alicante St. 951475 303 351.0 96 960
500015.0 Cantuba, Fe Alicante St. 017010-02 1505 1514.5 19 190
500249.0 Constantino, Marivic Alicante St. 028469-02 1745 1750.5 11 110
501129.0 Constantino, Pascual Alicante St. nan 372 387.0 30 300
500012.0 Dejucos, Lony Alicante St. 958902 0 0.0 0 0
501411.0 Dein, Sharon Alicante St. nan 32 32.0 0 0
500523.0 Dejumo, Jenalyn Alicante St. 017144-02 0 0.0 0 0
501024.0 Dejumo, Sergia Alicante St. nan 0 0.0 0 0
500316.0 Delariarte, Nicanor Alicante St. 027451-02 3645 3665.0 40 400
500357.0 Elloso, Amy Alicante St. nan 0 0.0 0 0
501105.0 Elloso, Amy/Card Bank Alicante St. 6V1997 239 252.5 27 270
500985.0 Escorel, Potito Alicante St. 17881 861 862.0 2 20
501022.0 Espa√±ol, Ave Alicante St. 70412 31 31.5 1 10
501379.0 Esparrago, Eden Alicante St. nan 367 369.0 4 40
500340.0 Espares, Junard Alicante St. nan 3152 3224.0 144 1440
500552.0 Espenida, Nita Alicante St. 027564-02 3389 3408.5 39 390
500264.0 Espenilla, Rosito Alicante St. 89300 1708 1745.0 74 740
500905.0 Espenilla, Rosito (B) Alicante St. nan 2502 2521.0 38 380
500146.0 Espinosa, Carlos Alicante St. 957520 5598 5623.0 50 500
500563.0 Espinosa, Emily Alicante St. 017798-02 2526 2530.5 9 90
500781.0 Flores, Berwin Alicante St. nan 2025 2025.0 0 0
501316.0 Flores, Christian Alicante St. nan 48 48.0 0 0
500564.0 Flores, Danilo Alicante St. 86907 0 0.0 0 0
501558.0 Gallano, Azenith Alicante St. nan 2 2.0 0 0
501690.0 Gallinera, John Mark Alicante St. nan 41 62.0 42 420
501332.0 Gebelaguin, Jenlyn Alicante St. nan 1379 1379.0 0 0
500711.0 Gebelaguin, Jesus Alicante St. nan 858 865.0 14 140
501025.0 Gelotin, Gemma Alicante St. nan 253 267.5 29 290
501023.0 Generoso, Ernesto Alicante St. nan 27 27.0 0 0
501289.0 Gestole,Chosen Alicante St. nan 1503 1508.5 11 110
500461.0 Grencio, Ramir Alicante St. nan 0 0.0 0 0
500623.0 Grencio, Maribel Alicante St. nan 191 207.5 33 330
500008.0 Genova, Erlinda Alicante St. 966416 1725 1728.5 7 70
500760.0 Gicaro, Efamar Alicante St. nan 125 131.0 12 120
501306.0 Gulmatico, Rodel Alicante St. nan 1068 1081.0 26 260
501613.0 Gutierrez, Reynald Alicante St. nan 403 433.5 61 610
501518.0 Granado, Cecilia Alicante St. nan 434 436.0 4 40
501128.0 Ida, Marife Alicante St. nan 478 478.0 0 0
500010.0 Jardin, Eden Alicante St. 957121 66 73.5 15 150
500907.0 Javier, Elena Alicante St. nan 1948 1959.5 23 230
500910.0 Kingdom of Jehova¬ís Witnesses Alicante St. 027634-02 0 0.0 0 0
500178.0 Laila, Vilma Alicante St. 6886956 9023 9085.0 124 1240
500559.0 Laurio, Josefa Alicante St. nan 99 105.0 12 120
500284.0 Leonor, Loreto (A) Alicante St. 205000532 17042 17209.0 334 3340
500378.0 Leonor, Loreto (B)/Rivero, Erwin Alicante St. 9588127 287 287.0 0 0
500717.0 Letada, Gener Alicante St. 028114-02 0 0.0 0 0
500013.0 Lique, Esteban Alicante St. 20500534 3790 3805.5 31 310
500794.0 Llacer, Mary Grace Alicante St. nan 328 350.5 45 450
500408.0 Lumberio, Belinda Alicante St. nan 5464 5475.5 23 230
500973.0 Lumberio, Belinda 2 Alicante St. nan 162 165.0 6 60
500475.0 Lumberio, Marvin Alicante St. nan 516 541.0 50 500
500986.0 Lumberio, Ramon Alicante St. nan 0 0.0 0 0
501344.0 Macabuhay, Henry Alicante St. nan 140 150.5 21 210
500250.0 Macabuhay, Wilferdo Alicante St. 951511 379 411.0 64 640
500789.0 Macoy, Cyrus Alicante St. 487 502 536.0 68 680
500978.0 Magayanes, Ruel Alicante St. nan 1678 1691.0 26 260
501620.0 Magdaraog, Felix III Alicante St. nan 122 122.0 0 0
500650.0 Martinez, Dante Alicante St. nan 2531 2546.0 30 300
500980.0 Martinez, Vincent Alicante St. nan 0 0.0 0 0
501481.0 Mercado, Judith Alicante St. nan 527 565.5 77 770
500271.0 Mores, Rosario Alicante St. nan 0 0.0 0 0
500093.0 Moya, Crispina Alicante St. 017819-02 1782 1798.5 33 330
500839.0 Ontog, Chita Alicante St. 61222355 3855 3896.5 83 830
501088.0 Pamotillo, Eva Alicante St. nan 1729 1741.5 25 250
500265.0 Ramos, Doroteo Alicante St. nan 0 0.0 0 0
500241.0 Recto, Nerissa Alicante St. 9005275 3211 3282.0 142 1420
500270.0 Rejuso, Ceddy Alicante St. nan 489 510.0 42 420
501425.0 Rejuso, James Alicante St. nan 622 644.5 45 450
500011.0 Rico, Esperanza Alicante St. nan 2063 2072.0 18 180
500723.0 Rilles, Flordeliza Alicante St. nan 0 0.0 0 0
500487.0 Sese, Robert Alicante St. nan 0 0.0 0 0
500203.0 Sopsop, Evelyn Alicante St. nan 1364 1364.0 0 0
500941.0 Tarrobal, Amiel Alicante St. nan 192 194.5 5 50
500584.0 Tarrobal, Leny Alicante St. 954885 3214 3222.5 17 170
500368.0 Tugbo, Nixon Alicante St. 017734-02 3600 3611.0 22 220
500381.0 UCCP Alicante St. 955353 6795 6846.5 103 1030
500911.0 Villahermosa, Benjamin Alicante St. 108022-02 0 0.0 0 0
500356.0 Villahermosa, Lita Alicante St. 96903254 1050 1053.5 7 70
500170.0 Villahermosa, Pedro Alicante St. 027570-02 3266 3319.5 107 1070
500633.0 Villahermosa, Sonia Alicante St. 028508-02 0 0.0 0 0
501428.0 Villahermosa, Jenny Alicante St. nan 771 797.0 52 520
500726.0 Villamor, Arne Alicante St. 1754 394 433.5 79 790
500984.0 Villamor, Belen Alicante St. 2834202 371 382.0 22 220
501291.0 Herato, Jovelyn Alicante St. nan 741 745.5 9 90
500399.0 Villamor, Emily Alicante St. 028342-02 2518 2518.0 0 0
501324.0 Villamor, Ricky Alicante St. nan 391 394.0 6 60
501219.0 Villamor,Fulceda Alicante St. 028145-02 858 865.5 15 150
500056.0 Villamor, Joel Alicante St. nan 3244 3261.5 35 350
500683.0 Ca√±ares, Marlon Almonte St. 017824-02 0 0.0 0 0
501177.0 Delavin, Zonrico Almonte St. nan 0 0.0 0 0
500815.0 Delavin, Zonrico 2 Almonte St. nan 0 0.0 0 0
501218.0 Delavin, Zonrico 3 Almonte St. nan 0 0.0 0 0
501067.0 Espenilla, Marina Almonte St. nan 0 0.0 0 0
500983.0 Espinosa, Aris Almonte St. 17768 7836 7869.0 66 660
500988.0 JMH Foundation Inc. Almonte St. nan 0 0.0 0 0
501294.0 Liceo De Sn. Jto. c/o Atty. Merillo Almonte St. nan 3371 3371.0 0 0
500082.0 LSJ Almonte St. 017814-02 7291 7419.0 256 2560
501450.0 Macoy, Besilda Almonte St. 018035-02 5376 5792.5 833 8330
501285.0 Omilgo, Michelle Almonte St. 12-125484 1011 1072.0 122 1220
500832.0 Laila, Aida Marie Almonte St. 027976-02 8731 8731.0 0 0
501529.0 LSJFI NEW BLDG Almonte St. nan 714 806.5 185 1850
500118.0 Abejero, Ernesto Jr. Altarejos St. 017147-02 6260 6289.0 58 580
501241.0 Amante, Nerissa Altarejos St. nan 1593 1605.5 25 250
500072.0 Alcantara, Rector Altarejos St. 151748 2143 2143.0 0 0
500810.0 Almerol, Nilo Altarejos St. nan 191 199.5 17 170
501534.0 Almi√±e, Nixon Altarejos St. nan 14 15.0 2 20
500447.0 Almodiel, Fe Altarejos St. 151660 6309 6325.0 32 320
500809.0 Almodiel, Merly Altarejos St. 798 1527 1533.0 12 120
500483.0 Almoete, Aleli Altarejos St. 9588453 688 697.5 19 190
500443.0 Almoete, Arles Altarejos St. 028661-02 2341 2341.0 0 0
501474.0 Almonte, Michelle Altarejos St. nan 460 475.5 31 310
500215.0 Almojuela, Junie Altarejos St. 151758 127 135.5 17 170
500043.0 Almojuela, Segundino Altarejos St. 017239-02 1956 1958.0 4 40
501645.0 Almoradie, Jose Altarejos St. nan 31 47.0 32 320
500149.0 Atabay, Elisa Altarejos St. 44935 0 0.0 0 0
500741.0 Arevalo, Amy Altarejos St. 029107-02 102 58.0 -88 -880
501026.0 Barrun, Ana Altarejos St. nan 293 320.5 55 550
500164.0 Barrun, Consolador Altarejos St. 017873-02 0 0.0 0 0
501216.0 Barrun, Panina Altarejos St. nan 1374 1394.0 40 400
500836.0 Barrun, Roderico Altarejos St. nan 0 0.0 0 0
501667.0 Barrun, Siony Altarejos St. nan 20 20.0 0 0
500258.0 Barrun, Ronnie/Barrun, Jerson Altarejos St. 018061-02 829 853.5 49 490
500824.0 Bartolata, Adolfo Altarejos St. nan 0 0.0 0 0
501494.0 Bartolata, Antonio Altarejos St. nan 2586 2613.0 54 540
500551.0 Bartolata, Danilo Altarejos St. nan 6982 7021.5 79 790
501487.0 Bartolata, Felicisima Altarejos St. nan 3474 3509.5 71 710
500205.0 Bartolata, Melchor Altarejos St. 028917-02 2186 2187.5 3 30
500595.0 Bartolay, Albert Altarejos St. 017828-02 1964 1973.0 18 180
501027.0 Bartolay, Diosdado Altarejos St. nan 930 940.5 21 210
500158.0 Bartolay, Dominador Altarejos St. 9310910 469 469.0 0 0
500071.0 Bartolay, Licel Altarejos St. 017816-02 16199 16307.5 217 2170
501415.0 Bartolay, Roald Altarejos St. nan 191 194.0 6 60
500204.0 Bartolay, Victor Altarejos St. 301748 186 202.0 32 320
501419.0 Cabiles, Solon Altarejos St. nan 1284 1344.5 121 1210
500200.0 Cantre, Vilma Altarejos St. 017880-02 2321 2331.5 21 210
500888.0 Carillo, Mida Altarejos St. 027637-02 984 984.0 0 0
501165.0 Dejumo, Adam Altarejos St. nan 0 0.0 0 0
500719.0 Dejumo, Rowena Altarejos St. 18060 0 0.0 0 0
500144.0 Delariarte, Evelyn Altarejos St. 018070-02 619 641.0 44 440
501077.0 Delariarte, Jenel Altarejos St. nan 947 962.5 31 310
500156.0 Delariarte, Vibiana Altarejos St. 44826 2960 2978.5 37 370
500805.0 Delavin, Seth Altarejos St. 027826-02 3362 3365.5 7 70
500652.0 Delfin, Nena Fatima Altarejos St. nan 3955 3982.0 54 540
500948.0 Delos Santos, Nena Altarejos St. 017802-02 0 0.0 0 0
500933.0 Espa√±ola, Lourdes Altarejos St. 017032-02 2935 2949.0 28 280
500155.0 Esparrago, Melchor Altarejos St. 95799 2613 2633.0 40 400
500534.0 Espenilla, Eden Altarejos St. nan 0 0.0 0 0
500137.0 Espinosa, Ader Altarejos St. 028191-02 5315 5328.5 27 270
500587.0 Espinosa, Jerol Altarejos St. nan 3081 3082.5 3 30
501089.0 Espinosa, Jerol (B) Altarejos St. nan 4354 4359.5 11 110
500069.0 Espinosa, Tito Altarejos St. 957116 191 216.0 50 500
501153.0 Garamay, Eugene Altarejos St. H19487 429 448.0 38 380
500117.0 Garamay, Pio Altarejos St. 017235-02 2932 2963.5 63 630
500982.0 Genova, Amilyn Altarejos St. nan 1158 1176.0 36 360
500766.0 Grafilo, Remedios Altarejos St. nan 1426 1433.0 14 140
500199.0 Laila, Eugene Altarejos St. 954257 0 0.0 0 0
500171.0 Letada, Felomino Altarejos St. 027563-02 3533 3552.5 39 390
500105.0 Lignes, Maria Altarejos St. 95744 6656 6738.0 164 1640
500822.0 Lique, Amalia Altarejos St. 017236-02 2744 2768.5 49 490
500590.0 Lumberio, Caridad Altarejos St. 017821-02 0 3528.5 7057 70570
500186.0 Marcos, Angelica Altarejos St. 957970 28 41.0 26 260
500596.0 Mi√±a, Marife Altarejos St. 2493 334 354.5 41 410
501019.0 Nerry, Aldrich Altarejos St. nan 3110 3113.0 6 60
500768.0 Poblete, Ana Altarejos St. nan 2681 2691.5 21 210
500172.0 Rejuso, Caridad Altarejos St. nan 0 0.0 0 0
500705.0 Rejuso, Cristy Altarejos St. 51159171 3600 3608.5 17 170
500620.0 Rejuso, Janeth Altarejos St. 017147-02 6912 6915.5 7 70
500703.0 Rejuso, Nicanor Altarejos St. 081054-02 2727 2735.0 16 160
500129.0 Romblon, Ariel Altarejos St. 886210 1016 1048.5 65 650
501092.0 Santiago, Nelsie Altarejos St. nan 0 0.0 0 0
500190.0 Sola, Ana Altarejos St. 958431 5192 5245.0 106 1060
500704.0 Sola, Andres Jr. Altarejos St. nan 0 0.0 0 0
500070.0 Torrecampo, Juden Altarejos St. 17231 2539 2562.0 46 460
500140.0 Velo, Lolita Altarejos St. 017739-02 4616 4645.5 59 590
500616.0 Yanson, Danilo Altarejos St. 9666641 2084 2097.5 27 270
500772.0 Abrera, Julius Amican St. nan 3765 3773.0 16 160
501224.0 Almerol, Salvador Amican St. 029034-02 3652 3708.5 113 1130
501581.0 Almine, Jimmy Amican St. nan 447 478.0 62 620
501220.0 Almocera, Francisco Jr. Amican St. 028141-02 566 577.5 23 230
501284.0 A√±onuevo, Susan Amican St. nan 465 495.0 60 600
501485.0 Barsaga, Neselie Amican St. nan 0 0.0 0 0
501234.0 Bartolay, Leny Amican St. nan 0 0.0 0 0
501464.0 Bartolay, Erle Amican St. nan 1031 1049.5 37 370
501424.0 Bartolata, Amaro Jr. Amican St. nan 490 502.5 25 250
501448.0 Bartolata, Mae Amican St. nan 438 444.0 12 120
500838.0 Barrun, Genina Amican St. 10793815 485 500.0 30 300
501571.0 Barrun, Jonalyn Amican St. nan 205 230.5 51 510
501512.0 Barrun, Marlon Amican St. nan 896 911.0 30 300
501629.0 Baruelo, Melben Amican St. nan 163 180.5 35 350
501642.0 Beroy, Salvacion Amican St. nan 266 289.5 47 470
501560.0 Bragais, Janeth Amican St. nan 226 243.5 35 350
501427.0 Cabiles, Christoper Amican St. nan 1052 1056.0 8 80
501568.0 Ca√±ares, Marissa Amican St. nan 231 249.0 36 360
501578.0 Cantre, Roger Amican St. nan 302 325.0 46 460
501208.0 Carranza, Maria Amican St. 511-103442 767 789.0 44 440
500713.0 Dejumo, Jomel Amican St. 51171329 165 177.0 24 240
501468.0 Dejumo, Marian Amican St. nan 490 500.0 20 200
501307.0 Delavin, Jori Amican St. nan 0 0.0 0 0
501553.0 Delavin, Junmar Amican St. nan 78 84.5 13 130
500332.0 Delos Santos, Pablo Amican St. nan 0 0.0 0 0
501438.0 Dilao, Jolly Amican St. 018064-02 347 360.5 27 270
501423.0 Dimanarig, Armin Amican St. nan 671 680.0 18 180
500636.0 Espenilla, Elvie Amican St. 971209637 0 0.0 0 0
501072.0 Gaurano, Alvin Amican St. 1378097 68 70.0 4 40
500889.0 Espinosa, Lilibeth Amican St. 27633 4911 4911.0 0 0
501212.0 Espinosa, Luz Amican St. 9511097 2470 2508.5 77 770
500188.0 Espinosa, Orlando Amican St. 029038-02 1182 1221.5 79 790
501367.0 Garamay, Arnold Amican St. nan 286 304.0 36 360
501365.0 Gaurano, Aljon Amican St. nan 724 739.5 31 310
500225.0 Gaurano, Maricel Amican St. 32356 0 0.0 0 0
500535.0 Giroy, Marissa Amican St. 15046869 0 0.0 0 0
501632.0 Gilaga, Silma Amican St. nan 82 91.0 18 180
501233.0 Gerna, Shirley Amican St. 50412826 562 562.0 0 0
500147.0 Granado, Florendo Amican St. 35086 2185 2186.5 3 30
500181.0 Granado, Job Amican St. 028451-02 136 144.5 17 170
500148.0 Inson, Jose Marcelo Amican St. 3288 2861 2892.0 62 620
501440.0 Laila, Rhea Amican St. nan 33 35.0 4 40
500162.0 Lique, Jeanne Amican St. 958451 7132 7146.5 29 290
501557.0 Llanto, Arnel Amican St. nan 127 135.0 16 160
500816.0 Marfil, Gina Amican St. 9311336 0 0.0 0 0
501559.0 Portrias, Macario Jr. Amican St. nan 104 117.5 27 270
500080.0 Rejuso, Rene Amican St. nan 79 91.0 24 240
501528.0 Reluao, Ernes Amican St. nan 170 170.0 0 0
500081.0 Sola, Julio Amican St. 724240-02 2196 2219.0 46 460
501336.0 So, Norven Amican St. 017238-02 1509 1529.5 41 410
501467.0 So, Melboi Amican St. nan 579 589.5 21 210
501562.0 So, Ryan Amican St. nan 190 215.5 51 510
500160.0 Villamor, Ariosto Amican St. nan 344 393.5 99 990
500157.0 Villamor, Carlos Amican St. nan 536 548.5 25 250
500161.0 Villamor, Jose Amican St. 957521 2644 2659.5 31 310
500243.0 Villamor, Leny Amican St. 9587477 3605 3638.0 66 660
501640.0 Villamor, Mary Joy Amican St. nan 101 124.5 47 470
501418.0 Villamor, Villand Amican St. 815016704 786 812.5 53 530
500541.0 Abejero, Leandro Bailon St. nan 2867 2893.0 52 520
500374.0 Acibar, Jenlin Bailon St. nan 1269 1315.5 93 930
500887.0 Adiaton, Gomer Bailon St. nan 0 0.0 0 0
501292.0 Aldave, Nora Bailon St. 028470-02 0 3955.0 7910 79100
501472.0 Aldave, Nora 2 Bailon St. nan 925 941.0 32 320
501386.0 Albiola, Ofelia Bailon St. 028574-02 774 793.0 38 380
501420.0 Alcala, Aldrin Bailon St. nan 784 813.5 59 590
500288.0 Alcantara, Luz-4 (Litay) Bailon St. nan 122 135.5 27 270
501015.0 Alcantara, Luz-1 (Jeaneth Bartolata Bailon St. 017876-02 157 184.5 55 550
500957.0 Alcantara, Luz-2 (Marivic) Bailon St. 91279 0 2.5 5 50
501002.0 Alcantara, Luz-3 (Luthche V.) Bailon St. 017807-02 0 30.5 61 610
501016.0 Alcantara, Luz-6   Bailon St. 91279 1517 1564.5 95 950
500748.0 Alcantara, Luz (Marl Bueta) Bailon St. 912-62 0 0.0 0 0
501201.0 Alcantara, Sheena Bailon St. 28949 1955 1963.0 16 160
500635.0 Alicante, Carlos Bailon St. nan 3922 3938.5 33 330
500224.0 Almedora, Tomas Bailon St. nan 2380 2406.0 52 520
500355.0 Almi√±e, Manuel Sr. Bailon St. 9667506 347 421.0 148 1480
500442.0 Almodal, Noe Bailon St. nan 836 930.0 188 1880
500389.0 Almodiel, Edgar Bailon St. 9521894 0 0.0 0 0
500686.0 Almoete, Gil Bailon St. 028250-02 0 0.0 0 0
501221.0 Almoete, Alex Bailon St. 956739 1162 1195.0 66 660
500835.0 Almosara, Janet Bailon St. 93-10825 6228 6228.0 0 0
500840.0 Almosara, Jose Bailon St. 5468 153 160.5 15 150
501288.0 Almosera, Josie Bailon St. 10898 427 447.0 40 400
501309.0 Almosera, Pio Bailon St. nan 1154 1181.0 54 540
500758.0 Altarejos, Ciceron Bailon St. nan 0 0.0 0 0
501526.0 Altarejos, Manuel Churchill (1) Bailon St. nan 232 237.5 11 110
501638.0 Altarejos, Manuel Churchill (2) Bailon St. nan 280 286.0 12 120
500756.0 Altiche, Lolita Bailon St. 2200103 4990 5070.5 161 1610
500466.0 Altiche, Nonilon Bailon St. 028947-02 2607 2621.5 29 290
500304.0 Amitaf Mini Shoppe Bailon St. nan 1229 1251.5 45 450
500328.0 Arcenas, Juancho Bailon St. 202008 2548 2548.0 0 0
500371.0 Aruc, Grace Bailon St. 027458-02 967 996.0 58 580
500298.0 Bailon, Junil Bailon St. nan 0 0.0 0 0
501382.0 Balingasa, Maria Elena Bailon St. 10114796 0 0.0 0 0
500515.0 Ibanez, Stella Marie Bailon St. 200404319 2552 2560.0 16 160
500826.0 Barredo, Edgar Bailon St. 028981-02 0 0.0 0 0
501178.0 Barredo, Edgar (Bakery) Bailon St. 027698-02 1988 2008.0 40 400
500349.0 Balt, Mora Bailon St. nan 5018 5072.0 108 1080
500233.0 Barruga, Helen Bailon St. 027698-02 4125 4129.0 8 80

In [ ]:
import csv

# Create the output directory if it doesn't exist
mar_output_dir = os.path.dirname("../../dataset/raw/2020/MAR2020.csv")
apr_output_dir = os.path.dirname("../../dataset/raw/2020/APR2020.csv")
os.makedirs(mar_output_dir, exist_ok=True)
os.makedirs(apr_output_dir, exist_ok=True)

with open("../../dataset/raw/2020/MAR2020.csv", "w", newline="", encoding='latin-1') as mar_file \
    , open("../../dataset/raw/2020/APR2020.csv", "w", newline="", encoding='latin-1') as apr_file:
    mar_csv_writer = csv.writer(mar_file)
    apr_csv_writer = csv.writer(apr_file)
    # Write header
    mar_csv_writer.writerow([
        "Control Number", "Consumer's Name", "Address", 
        "Water Meter Serial #", "Previous", "Present", 
        "Cons.", "Amount"
    ])
    apr_csv_writer.writerow([
        "Control Number", "Consumer's Name", "Address", 
        "Water Meter Serial #", "Previous", "Present", 
        "Cons.", "Amount"
    ])

    for index, row in df.iterrows():
        try:
            control_number = row["Control Number"]
            consumer_name = row["Consumer's Name"]
            address = row["Address"]
            serial_number = row["Water Meter Serial #"]
            
            # Handle Previous Reading
            try:
                mar_previous_reading = int(float(str(row["Previous"]).strip() or 0))
            except (ValueError, TypeError):
                mar_previous_reading = 0
            
            # Handle Present Reading
            try:
                mar_present_reading = int(float(str(row["Present"]).strip() or 0))
            except (ValueError, TypeError):
                mar_present_reading = mar_previous_reading  # Default to previous reading if present is invalid
            
            # Calculate values for March
            mar_current_reading = mar_previous_reading + round((mar_present_reading - mar_previous_reading) / 2)
            mar_total_consumption = mar_current_reading - mar_previous_reading
            mar_total_amount = mar_total_consumption * 10 

            new_record_mar = [
                control_number, consumer_name, address, serial_number,
                mar_previous_reading, round(mar_current_reading),
                mar_total_consumption, mar_total_amount
            ]

            # Calculate values April
            apr_previous_reading = mar_current_reading
            
            # Handle Present Reading
            try:
                apr_current_reading = int(float(str(row["Present"]).strip() or 0))
            except (ValueError, TypeError):
                apr_current_reading = apr_previous_reading
            
            # Calculate values for April
            apr_total_consumption = apr_current_reading - apr_previous_reading
            apr_total_amount = apr_total_consumption * 10 

            new_record_apr = [
                control_number, consumer_name, address, serial_number,
                apr_previous_reading, round(apr_current_reading),
                apr_total_consumption, apr_total_amount
            ]            
            # Print Record
            print(f"Processed MAR {index} rows: {new_record_mar}")
            print(f"Processed APR {index} rows: {new_record_apr}")
            
            # Write row
            mar_csv_writer.writerow(new_record_mar)
            apr_csv_writer.writerow(new_record_apr)                
        except Exception as e:
            print(f"Error processing row {index}: {e}")
            continue

print("Processing complete!")

Processed MAR 0 rows: [501549.0, 'Alba√±o, Lilane', 'Alicante St.', nan, 218, 232, 14, 140]
Processed MAR 1 rows: [500750.0, 'Aljecera, Marcelino', 'Alicante St.', nan, 3030, 3040, 10, 100]
Processed MAR 2 rows: [500990.0, 'Almi√±ana, Irus', 'Alicante St.', nan, 471, 504, 33, 330]
Processed MAR 3 rows: [500505.0, 'Almi√±e, Edison', 'Alicante St.', '95022096', 2, 32, 30, 300]
Processed MAR 4 rows: [501542.0, 'Almi√±e, Filben', 'Alicante St.', nan, 3271, 3293, 22, 220]
Processed MAR 5 rows: [500431.0, 'Almi√±e, Franchie', 'Alicante St.', '121006093', 0, 0, 0, 0]
Processed MAR 6 rows: [500263.0, 'Almodal, Arna', 'Alicante St.', '9588526', 5228, 5240, 12, 120]
Processed MAR 7 rows: [501240.0, 'Almocera, Owen', 'Alicante St.', nan, 67, 103, 36, 360]
Processed MAR 8 rows: [500484.0, 'Almodal, Erlinda', 'Alicante St.', '028086-02', 0, 0, 0, 0]
Processed MAR 9 rows: [500739.0, 'Almodal, Jolly', 'Alicante St.', '017902-02', 1795, 1861, 66, 660]
Processed MAR 10 rows: [500544.0, 'Almodal, Noe', 'Alicante St.', nan, 2418, 2418, 0, 0]
Processed MAR 11 rows: [500187.0, 'Almodiel, Arles', 'Alicante St.', '9074313', 3210, 3210, 0, 0]
Processed MAR 12 rows: [501447.0, 'Almodiel, Mary Grace', 'Alicante St.', nan, 238, 240, 2, 20]
Processed MAR 13 rows: [501453.0, 'Alcantara, Hilda', 'Alicante St.', nan, 183, 189, 6, 60]
Processed MAR 14 rows: [501317.0, 'Almoete, Ike', 'Alicante St.', nan, 595, 603, 8, 80]
Processed MAR 15 rows: [501280.0, 'Almojuela, Arlic', 'Alicante St.', nan, 424, 448, 24, 240]
Processed MAR 16 rows: [500248.0, 'Almojuela, Rogelio', 'Alicante St.', '956320', 6706, 6745, 39, 390]
Processed MAR 17 rows: [501028.0, 'Almoradie, Marites', 'Alicante St.', nan, 1914, 1924, 10, 100]
Processed MAR 18 rows: [501437.0, 'Almoradie, Geann', 'Alicante St.', nan, 1386, 1437, 51, 510]
Processed MAR 19 rows: [500433.0, 'Almoradie, Marina', 'Alicante St.', nan, 340, 369, 29, 290]
Processed MAR 20 rows: [500260.0, 'Altiche, Antonio', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 21 rows: [501663.0, 'Altiche, Nenita', 'Alicante St.', nan, 56, 56, 0, 0]
Processed MAR 22 rows: [500185.0, 'Aspa, Leny', 'Alicante St.', '245534', 1518, 1522, 4, 40]
Processed MAR 23 rows: [500169.0, 'A√±onuevo, Paz', 'Alicante St.', '027568-02', 3162, 3162, 0, 0]
Processed MAR 24 rows: [501232.0, 'Anabe, Antonio', 'Alicante St.', '08-82569', 0, 0, 0, 0]
Processed MAR 25 rows: [500479.0, 'Azares, Jeffrey', 'Alicante St.', '028462-02', 64, 82, 18, 180]
Processed MAR 26 rows: [500009.0, 'Barruga, Expedito', 'Alicante St.', '017766-02', 2014, 2024, 10, 100]
Processed MAR 27 rows: [500472.0, 'Barruga, Loreto', 'Alicante St.', '028652-02', 814, 849, 35, 350]
Processed MAR 28 rows: [501393.0, 'Barrun, Ana', 'Alicante St.', '028576-02', 602, 623, 21, 210]
Processed MAR 29 rows: [500094.0, 'Barrun, Divina', 'Alicante St.', '954950', 2703, 2722, 19, 190]
Processed MAR 30 rows: [501020.0, 'Barrun, Emilio', 'Alicante St.', nan, 1995, 2013, 18, 180]
Processed MAR 31 rows: [500692.0, 'Barrun, Jose', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 32 rows: [500585.0, 'Barrun, Nida', 'Alicante St.', nan, 321, 347, 26, 260]
Processed MAR 33 rows: [500330.0, 'Barrun, Vito', 'Alicante St.', '151228', 0, 16, 16, 160]
Processed MAR 34 rows: [501260.0, 'Barsaga, Natividad', 'Alicante St.', '11075846', 130, 172, 42, 420]
Processed MAR 35 rows: [501330.0, 'Barsaga, Natividad 2', 'Alicante St.', nan, 66, 66, 0, 0]
Processed MAR 36 rows: [501167.0, 'Bartolabac, Renato', 'Alicante St.', nan, 1273, 1287, 14, 140]
Processed MAR 37 rows: [500740.0, 'Bartolata, Jose', 'Alicante St.', '017903-02', 0, 0, 0, 0]
Processed MAR 38 rows: [500278.0, 'Bartolay, Felipe', 'Alicante St.', '028463-02', 1878, 1892, 14, 140]
Processed MAR 39 rows: [500861.0, 'Bartolata, Lourdes', 'Alicante St.', '957925', 2189, 2201, 12, 120]
Processed MAR 40 rows: [501021.0, 'Bartolay, Isaias', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 41 rows: [500254.0, 'Bartolay, Nilda', 'Alicante St.', '028194-02', 1804, 1805, 1, 10]
Processed MAR 42 rows: [501301.0, 'Bartolay, Nilo', 'Alicante St.', nan, 910, 920, 10, 100]
Processed MAR 43 rows: [501048.0, 'Bartolay, Nolyn', 'Alicante St.', nan, 496, 532, 36, 360]
Processed MAR 44 rows: [500095.0, 'Bartolay, Rustom', 'Alicante St.', '9521569', 1322, 1332, 10, 100]
Processed MAR 45 rows: [501176.0, 'Bartolay, Marites', 'Alicante St.', '10092103', 0, 858, 858, 8580]
Processed MAR 46 rows: [500045.0, 'Bartolay, Orlando', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 47 rows: [500405.0, 'Bartolay, Orlando', 'Alicante St.', nan, 1571, 1578, 7, 70]
Processed MAR 48 rows: [500380.0, 'Borejon, Melchor', 'Alicante St.', '20048213', 1064, 1071, 7, 70]
Processed MAR 49 rows: [501329.0, 'Borejon, Noli', 'Alicante St.', nan, 238, 256, 18, 180]
Processed MAR 50 rows: [500377.0, 'Borromeo, Elisa', 'Alicante St.', '9665024', 234, 247, 13, 130]
Processed MAR 51 rows: [501522.0, 'Borromeo, Gener', 'Alicante St.', nan, 166, 174, 8, 80]
Processed MAR 52 rows: [500251.0, 'Cabiles, Nicanor', 'Alicante St.', '970701083', 904, 942, 38, 380]
Processed MAR 53 rows: [500014.0, 'Canchela, Emma', 'Alicante St.', '954415', 3713, 3725, 12, 120]
Processed MAR 54 rows: [500262.0, 'Canchela, Isaias', 'Alicante St.', '952564', 2700, 2713, 13, 130]
Processed MAR 55 rows: [501676.0, 'Cantoria, Jose', 'Alicante St.', nan, 18, 30, 12, 120]
Processed MAR 56 rows: [500696.0, 'Cantoria, Lourdes', 'Alicante St.', '951475', 303, 351, 48, 480]
Processed MAR 57 rows: [500015.0, 'Cantuba, Fe', 'Alicante St.', '017010-02', 1505, 1515, 10, 100]
Processed MAR 58 rows: [500249.0, 'Constantino, Marivic', 'Alicante St.', '028469-02', 1745, 1751, 6, 60]
Processed MAR 59 rows: [501129.0, 'Constantino, Pascual', 'Alicante St.', nan, 372, 387, 15, 150]
Processed MAR 60 rows: [500012.0, 'Dejucos, Lony', 'Alicante St.', '958902', 0, 0, 0, 0]
Processed MAR 61 rows: [501411.0, 'Dein, Sharon', 'Alicante St.', nan, 32, 32, 0, 0]
Processed MAR 62 rows: [500523.0, 'Dejumo, Jenalyn', 'Alicante St.', '017144-02', 0, 0, 0, 0]
Processed MAR 63 rows: [501024.0, 'Dejumo, Sergia', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 64 rows: [500316.0, 'Delariarte, Nicanor', 'Alicante St.', '027451-02', 3645, 3665, 20, 200]
Processed MAR 65 rows: [500357.0, 'Elloso, Amy', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 66 rows: [501105.0, 'Elloso, Amy/Card Bank', 'Alicante St.', '6V1997', 239, 253, 14, 140]
Processed MAR 67 rows: [500985.0, 'Escorel, Potito', 'Alicante St.', '17881', 861, 862, 1, 10]
Processed MAR 68 rows: [501022.0, 'Espa√±ol, Ave', 'Alicante St.', '70412', 31, 31, 0, 0]
Processed MAR 69 rows: [501379.0, 'Esparrago, Eden', 'Alicante St.', nan, 367, 369, 2, 20]
Processed MAR 70 rows: [500340.0, 'Espares, Junard', 'Alicante St.', nan, 3152, 3224, 72, 720]
Processed MAR 71 rows: [500552.0, 'Espenida, Nita', 'Alicante St.', '027564-02', 3389, 3409, 20, 200]
Processed MAR 72 rows: [500264.0, 'Espenilla, Rosito', 'Alicante St.', '89300', 1708, 1745, 37, 370]
Processed MAR 73 rows: [500905.0, 'Espenilla, Rosito (B)', 'Alicante St.', nan, 2502, 2521, 19, 190]
Processed MAR 74 rows: [500146.0, 'Espinosa, Carlos', 'Alicante St.', '957520', 5598, 5623, 25, 250]
Processed MAR 75 rows: [500563.0, 'Espinosa, Emily', 'Alicante St.', '017798-02', 2526, 2530, 4, 40]
Processed MAR 76 rows: [500781.0, 'Flores, Berwin', 'Alicante St.', nan, 2025, 2025, 0, 0]
Processed MAR 77 rows: [501316.0, 'Flores, Christian', 'Alicante St.', nan, 48, 48, 0, 0]
Processed MAR 78 rows: [500564.0, 'Flores, Danilo', 'Alicante St.', '86907', 0, 0, 0, 0]
Processed MAR 79 rows: [501558.0, 'Gallano, Azenith', 'Alicante St.', nan, 2, 2, 0, 0]
Processed MAR 80 rows: [501690.0, 'Gallinera, John Mark', 'Alicante St.', nan, 41, 62, 21, 210]
Processed MAR 81 rows: [501332.0, 'Gebelaguin, Jenlyn', 'Alicante St.', nan, 1379, 1379, 0, 0]
Processed MAR 82 rows: [500711.0, 'Gebelaguin, Jesus', 'Alicante St.', nan, 858, 865, 7, 70]
Processed MAR 83 rows: [501025.0, 'Gelotin, Gemma', 'Alicante St.', nan, 253, 267, 14, 140]
Processed MAR 84 rows: [501023.0, 'Generoso, Ernesto', 'Alicante St.', nan, 27, 27, 0, 0]
Processed MAR 85 rows: [501289.0, 'Gestole,Chosen', 'Alicante St.', nan, 1503, 1509, 6, 60]
Processed MAR 86 rows: [500461.0, 'Grencio, Ramir', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 87 rows: [500623.0, 'Grencio, Maribel', 'Alicante St.', nan, 191, 207, 16, 160]
Processed MAR 88 rows: [500008.0, 'Genova, Erlinda', 'Alicante St.', '966416', 1725, 1729, 4, 40]
Processed MAR 89 rows: [500760.0, 'Gicaro, Efamar', 'Alicante St.', nan, 125, 131, 6, 60]
Processed MAR 90 rows: [501306.0, 'Gulmatico, Rodel', 'Alicante St.', nan, 1068, 1081, 13, 130]
Processed MAR 91 rows: [501613.0, 'Gutierrez, Reynald', 'Alicante St.', nan, 403, 433, 30, 300]
Processed MAR 92 rows: [501518.0, 'Granado, Cecilia', 'Alicante St.', nan, 434, 436, 2, 20]
Processed MAR 93 rows: [501128.0, 'Ida, Marife', 'Alicante St.', nan, 478, 478, 0, 0]
Processed MAR 94 rows: [500010.0, 'Jardin, Eden', 'Alicante St.', '957121', 66, 74, 8, 80]
Processed MAR 95 rows: [500907.0, 'Javier, Elena', 'Alicante St.', nan, 1948, 1960, 12, 120]
Processed MAR 96 rows: [500910.0, 'Kingdom of Jehova\x92s Witnesses', 'Alicante St.', '027634-02', 0, 0, 0, 0]
Processed MAR 97 rows: [500178.0, 'Laila, Vilma', 'Alicante St.', '6886956', 9023, 9085, 62, 620]
Processed MAR 98 rows: [500559.0, 'Laurio, Josefa', 'Alicante St.', nan, 99, 105, 6, 60]
Processed MAR 99 rows: [500284.0, 'Leonor, Loreto (A)', 'Alicante St.', '205000532', 17042, 17209, 167, 1670]
Processed MAR 100 rows: [500378.0, 'Leonor, Loreto (B)/Rivero, Erwin', 'Alicante St.', '9588127', 287, 287, 0, 0]
Processed MAR 101 rows: [500717.0, 'Letada, Gener', 'Alicante St.', '028114-02', 0, 0, 0, 0]
Processed MAR 102 rows: [500013.0, 'Lique, Esteban', 'Alicante St.', '20500534', 3790, 3806, 16, 160]
Processed MAR 103 rows: [500794.0, 'Llacer, Mary Grace', 'Alicante St.', nan, 328, 350, 22, 220]
Processed MAR 104 rows: [500408.0, 'Lumberio, Belinda', 'Alicante St.', nan, 5464, 5476, 12, 120]
Processed MAR 105 rows: [500973.0, 'Lumberio, Belinda 2', 'Alicante St.', nan, 162, 165, 3, 30]
Processed MAR 106 rows: [500475.0, 'Lumberio, Marvin', 'Alicante St.', nan, 516, 541, 25, 250]
Processed MAR 107 rows: [500986.0, 'Lumberio, Ramon', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 108 rows: [501344.0, 'Macabuhay, Henry', 'Alicante St.', nan, 140, 150, 10, 100]
Processed MAR 109 rows: [500250.0, 'Macabuhay, Wilferdo', 'Alicante St.', '951511', 379, 411, 32, 320]
Processed MAR 110 rows: [500789.0, 'Macoy, Cyrus', 'Alicante St.', '487', 502, 536, 34, 340]
Processed MAR 111 rows: [500978.0, 'Magayanes, Ruel', 'Alicante St.', nan, 1678, 1691, 13, 130]
Processed MAR 112 rows: [501620.0, 'Magdaraog, Felix III', 'Alicante St.', nan, 122, 122, 0, 0]
Processed MAR 113 rows: [500650.0, 'Martinez, Dante', 'Alicante St.', nan, 2531, 2546, 15, 150]
Processed MAR 114 rows: [500980.0, 'Martinez, Vincent', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 115 rows: [501481.0, 'Mercado, Judith', 'Alicante St.', nan, 527, 565, 38, 380]
Processed MAR 116 rows: [500271.0, 'Mores, Rosario', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 117 rows: [500093.0, 'Moya, Crispina', 'Alicante St.', '017819-02', 1782, 1798, 16, 160]
Processed MAR 118 rows: [500839.0, 'Ontog, Chita', 'Alicante St.', '61222355', 3855, 3897, 42, 420]
Processed MAR 119 rows: [501088.0, 'Pamotillo, Eva', 'Alicante St.', nan, 1729, 1741, 12, 120]
Processed MAR 120 rows: [500265.0, 'Ramos, Doroteo', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 121 rows: [500241.0, 'Recto, Nerissa', 'Alicante St.', '9005275', 3211, 3282, 71, 710]
Processed MAR 122 rows: [500270.0, 'Rejuso, Ceddy', 'Alicante St.', nan, 489, 510, 21, 210]
Processed MAR 123 rows: [501425.0, 'Rejuso, James', 'Alicante St.', nan, 622, 644, 22, 220]
Processed MAR 124 rows: [500011.0, 'Rico, Esperanza', 'Alicante St.', nan, 2063, 2072, 9, 90]
Processed MAR 125 rows: [500723.0, 'Rilles, Flordeliza', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 126 rows: [500487.0, 'Sese, Robert', 'Alicante St.', nan, 0, 0, 0, 0]
Processed MAR 127 rows: [500203.0, 'Sopsop, Evelyn', 'Alicante St.', nan, 1364, 1364, 0, 0]
Processed MAR 128 rows: [500941.0, 'Tarrobal, Amiel', 'Alicante St.', nan, 192, 194, 2, 20]
Processed MAR 129 rows: [500584.0, 'Tarrobal, Leny', 'Alicante St.', '954885', 3214, 3222, 8, 80]
Processed MAR 130 rows: [500368.0, 'Tugbo, Nixon', 'Alicante St.', '017734-02', 3600, 3611, 11, 110]
Processed MAR 131 rows: [500381.0, 'UCCP', 'Alicante St.', '955353', 6795, 6847, 52, 520]
Processed MAR 132 rows: [500911.0, 'Villahermosa, Benjamin', 'Alicante St.', '108022-02', 0, 0, 0, 0]
Processed MAR 133 rows: [500356.0, 'Villahermosa, Lita', 'Alicante St.', '96903254', 1050, 1054, 4, 40]
Processed MAR 134 rows: [500170.0, 'Villahermosa, Pedro', 'Alicante St.', '027570-02', 3266, 3320, 54, 540]
Processed MAR 135 rows: [500633.0, 'Villahermosa, Sonia', 'Alicante St.', '028508-02', 0, 0, 0, 0]
Processed MAR 136 rows: [501428.0, 'Villahermosa, Jenny', 'Alicante St.', nan, 771, 797, 26, 260]
Processed MAR 137 rows: [500726.0, 'Villamor, Arne', 'Alicante St.', '1754', 394, 434, 40, 400]
Processed MAR 138 rows: [500984.0, 'Villamor, Belen', 'Alicante St.', '2834202', 371, 382, 11, 110]
Processed MAR 139 rows: [501291.0, 'Herato, Jovelyn', 'Alicante St.', nan, 741, 745, 4, 40]
Processed MAR 140 rows: [500399.0, 'Villamor, Emily', 'Alicante St.', '028342-02', 2518, 2518, 0, 0]
Processed MAR 141 rows: [501324.0, 'Villamor, Ricky', 'Alicante St.', nan, 391, 394, 3, 30]
Processed MAR 142 rows: [501219.0, 'Villamor,Fulceda', 'Alicante St.', '028145-02', 858, 866, 8, 80]
Processed MAR 143 rows: [500056.0, 'Villamor, Joel', 'Alicante St.', nan, 3244, 3262, 18, 180]
Processed MAR 144 rows: [500683.0, 'Ca√±ares, Marlon', 'Almonte St.', '017824-02', 0, 0, 0, 0]
Processed MAR 145 rows: [501177.0, 'Delavin, Zonrico', 'Almonte St.', nan, 0, 0, 0, 0]
Processed MAR 146 rows: [500815.0, 'Delavin, Zonrico 2', 'Almonte St.', nan, 0, 0, 0, 0]
Processed MAR 147 rows: [501218.0, 'Delavin, Zonrico 3', 'Almonte St.', nan, 0, 0, 0, 0]
Processed MAR 148 rows: [501067.0, 'Espenilla, Marina', 'Almonte St.', nan, 0, 0, 0, 0]
Processed MAR 149 rows: [500983.0, 'Espinosa, Aris', 'Almonte St.', '17768', 7836, 7869, 33, 330]
Processed MAR 150 rows: [500988.0, 'JMH Foundation Inc.', 'Almonte St.', nan, 0, 0, 0, 0]
Processed MAR 151 rows: [501294.0, 'Liceo De Sn. Jto. c/o Atty. Merillo', 'Almonte St.', nan, 3371, 3371, 0, 0]
Processed MAR 152 rows: [500082.0, 'LSJ', 'Almonte St.', '017814-02', 7291, 7419, 128, 1280]
Processed MAR 153 rows: [501450.0, 'Macoy, Besilda', 'Almonte St.', '018035-02', 5376, 5792, 416, 4160]
Processed MAR 154 rows: [501285.0, 'Omilgo, Michelle', 'Almonte St.', '12-125484', 1011, 1072, 61, 610]
Processed MAR 155 rows: [500832.0, 'Laila, Aida Marie', 'Almonte St.', '027976-02', 8731, 8731, 0, 0]
Processed MAR 156 rows: [501529.0, 'LSJFI NEW BLDG', 'Almonte St.', nan, 714, 806, 92, 920]
Processed MAR 157 rows: [500118.0, 'Abejero, Ernesto Jr.', 'Altarejos St.', '017147-02', 6260, 6289, 29, 290]
Processed MAR 158 rows: [501241.0, 'Amante, Nerissa', 'Altarejos St.', nan, 1593, 1605, 12, 120]
Processed MAR 159 rows: [500072.0, 'Alcantara, Rector', 'Altarejos St.', '151748', 2143, 2143, 0, 0]
Processed MAR 160 rows: [500810.0, 'Almerol, Nilo', 'Altarejos St.', nan, 191, 199, 8, 80]
Processed MAR 161 rows: [501534.0, 'Almi√±e, Nixon', 'Altarejos St.', nan, 14, 15, 1, 10]
Processed MAR 162 rows: [500447.0, 'Almodiel, Fe', 'Altarejos St.', '151660', 6309, 6325, 16, 160]
Processed MAR 163 rows: [500809.0, 'Almodiel, Merly', 'Altarejos St.', '798', 1527, 1533, 6, 60]
Processed MAR 164 rows: [500483.0, 'Almoete, Aleli', 'Altarejos St.', '9588453', 688, 698, 10, 100]
Processed MAR 165 rows: [500443.0, 'Almoete, Arles', 'Altarejos St.', '028661-02', 2341, 2341, 0, 0]
Processed MAR 166 rows: [501474.0, 'Almonte, Michelle', 'Altarejos St.', nan, 460, 476, 16, 160]
Processed MAR 167 rows: [500215.0, 'Almojuela, Junie', 'Altarejos St.', '151758', 127, 135, 8, 80]
Processed MAR 168 rows: [500043.0, 'Almojuela, Segundino', 'Altarejos St.', '017239-02', 1956, 1958, 2, 20]
Processed MAR 169 rows: [501645.0, 'Almoradie, Jose', 'Altarejos St.', nan, 31, 47, 16, 160]
Processed MAR 170 rows: [500149.0, 'Atabay, Elisa', 'Altarejos St.', '44935', 0, 0, 0, 0]
Processed MAR 171 rows: [500741.0, 'Arevalo, Amy', 'Altarejos St.', '029107-02', 102, 58, -44, -440]
Processed MAR 172 rows: [501026.0, 'Barrun, Ana', 'Altarejos St.', nan, 293, 321, 28, 280]
Processed MAR 173 rows: [500164.0, 'Barrun, Consolador', 'Altarejos St.', '017873-02', 0, 0, 0, 0]
Processed MAR 174 rows: [501216.0, 'Barrun, Panina', 'Altarejos St.', nan, 1374, 1394, 20, 200]
Processed MAR 175 rows: [500836.0, 'Barrun, Roderico', 'Altarejos St.', nan, 0, 0, 0, 0]
Processed MAR 176 rows: [501667.0, 'Barrun, Siony', 'Altarejos St.', nan, 20, 20, 0, 0]
Processed MAR 177 rows: [500258.0, 'Barrun, Ronnie/Barrun, Jerson', 'Altarejos St.', '018061-02', 829, 853, 24, 240]
Processed MAR 178 rows: [500824.0, 'Bartolata, Adolfo', 'Altarejos St.', nan, 0, 0, 0, 0]
Processed MAR 179 rows: [501494.0, 'Bartolata, Antonio', 'Altarejos St.', nan, 2586, 2613, 27, 270]
Processed MAR 180 rows: [500551.0, 'Bartolata, Danilo', 'Altarejos St.', nan, 6982, 7022, 40, 400]
Processed MAR 181 rows: [501487.0, 'Bartolata, Felicisima', 'Altarejos St.', nan, 3474, 3510, 36, 360]
Processed MAR 182 rows: [500205.0, 'Bartolata, Melchor', 'Altarejos St.', '028917-02', 2186, 2188, 2, 20]
Processed MAR 183 rows: [500595.0, 'Bartolay, Albert', 'Altarejos St.', '017828-02', 1964, 1973, 9, 90]
Processed MAR 184 rows: [501027.0, 'Bartolay, Diosdado', 'Altarejos St.', nan, 930, 940, 10, 100]
Processed MAR 185 rows: [500158.0, 'Bartolay, Dominador', 'Altarejos St.', '9310910', 469, 469, 0, 0]
Processed MAR 186 rows: [500071.0, 'Bartolay, Licel', 'Altarejos St.', '017816-02', 16199, 16307, 108, 1080]
Processed MAR 187 rows: [501415.0, 'Bartolay, Roald', 'Altarejos St.', nan, 191, 194, 3, 30]
Processed MAR 188 rows: [500204.0, 'Bartolay, Victor', 'Altarejos St.', '301748', 186, 202, 16, 160]
Processed MAR 189 rows: [501419.0, 'Cabiles, Solon', 'Altarejos St.', nan, 1284, 1344, 60, 600]
Processed MAR 190 rows: [500200.0, 'Cantre, Vilma', 'Altarejos St.', '017880-02', 2321, 2331, 10, 100]
Processed MAR 191 rows: [500888.0, 'Carillo, Mida', 'Altarejos St.', '027637-02', 984, 984, 0, 0]
Processed MAR 192 rows: [501165.0, 'Dejumo, Adam', 'Altarejos St.', nan, 0, 0, 0, 0]
Processed MAR 193 rows: [500719.0, 'Dejumo, Rowena', 'Altarejos St.', '18060', 0, 0, 0, 0]
Processed MAR 194 rows: [500144.0, 'Delariarte, Evelyn', 'Altarejos St.', '018070-02', 619, 641, 22, 220]
Processed MAR 195 rows: [501077.0, 'Delariarte, Jenel', 'Altarejos St.', nan, 947, 963, 16, 160]
Processed MAR 196 rows: [500156.0, 'Delariarte, Vibiana', 'Altarejos St.', '44826', 2960, 2978, 18, 180]
Processed MAR 197 rows: [500805.0, 'Delavin, Seth', 'Altarejos St.', '027826-02', 3362, 3366, 4, 40]
Processed MAR 198 rows: [500652.0, 'Delfin, Nena Fatima', 'Altarejos St.', nan, 3955, 3982, 27, 270]
Processed MAR 199 rows: [500948.0, 'Delos Santos, Nena', 'Altarejos St.', '017802-02', 0, 0, 0, 0]
Processed MAR 200 rows: [500933.0, 'Espa√±ola, Lourdes', 'Altarejos St.', '017032-02', 2935, 2949, 14, 140]
Processed MAR 201 rows: [500155.0, 'Esparrago, Melchor', 'Altarejos St.', '95799', 2613, 2633, 20, 200]
Processed MAR 202 rows: [500534.0, 'Espenilla, Eden', 'Altarejos St.', nan, 0, 0, 0, 0]
Processed MAR 203 rows: [500137.0, 'Espinosa, Ader', 'Altarejos St.', '028191-02', 5315, 5329, 14, 140]
Processed MAR 204 rows: [500587.0, 'Espinosa, Jerol', 'Altarejos St.', nan, 3081, 3083, 2, 20]
Processed MAR 205 rows: [501089.0, 'Espinosa, Jerol (B)', 'Altarejos St.', nan, 4354, 4360, 6, 60]
Processed MAR 206 rows: [500069.0, 'Espinosa, Tito', 'Altarejos St.', '957116', 191, 216, 25, 250]

In [71]:
# Read the data with optimized dtypes
dtypes = {
    'Control Number': 'str',
    "Consumer's Name": 'str',
    'Address': 'str',
    'Water Meter Serial #': 'str',
    'Previous': 'float64',
    'Present': 'float64',
    'Current': 'float64',
    'Cons.': 'float64',
    'Amount': 'float64'
}

# Read the CSV
new_df = pd.read_csv("../../dataset/raw/2020/APR2020.csv", 
                    encoding='latin-1',
                    dtype=dtypes)

# Check for negative consumption
print("=== Negative Consumption Summary ===")
neg_consumption = new_df[new_df['Cons.'] < 0]
print(f"Total rows with negative consumption: {len(neg_consumption)}")
if not neg_consumption.empty:
    print("\nSample of rows with negative consumption:")
    print(neg_consumption[['Control Number', 'Previous', 'Present', 'Cons.']].head())

# Check for negative amount
print("\n=== Negative Amount Summary ===")
neg_amount = new_df[new_df['Amount'] < 0]
print(f"Total rows with negative amount: {len(neg_amount)}")
if not neg_amount.empty:
    print("\nSample of rows with negative amount:")
    print(neg_amount[['Control Number', 'Cons.', 'Amount']].head())

# Additional checks
print("\n=== Additional Data Quality Checks ===")
print(f"Total rows: {len(new_df)}")
print(f"Rows with zero consumption: {len(new_df[new_df['Cons.'] == 0])}")
print(f"Rows with missing values: {new_df.isnull().any(axis=1).sum()}")

=== Negative Consumption Summary ===
Total rows with negative consumption: 1

Sample of rows with negative consumption:
    Control Number  Previous  Present  Cons.
171       500741.0      58.0     14.0  -44.0

=== Negative Amount Summary ===
Total rows with negative amount: 1

Sample of rows with negative amount:
    Control Number  Cons.  Amount
171       500741.0  -44.0  -440.0

=== Additional Data Quality Checks ===
Total rows: 1633
Rows with zero consumption: 544
Rows with missing values: 698