## Data Exploration of the Tabular Consumption Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [5]:
df_consumption = pd.read_csv("../../dataset/clean/production/tabular/consumption_consolidated.csv")
df_consumption.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121,"Almodal, Maricel",District 2,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
2,50964,"Esparraguerra, Irish",District 2,Fabmar Street,Residential,Unknown,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,500001,"Encinares, Roberto",District 4,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
4,500002,"Pareja, Myrna",District 4,Esparrago Street,Residential,Active,153.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,13.0,5.0,18.0,10.0,0.0,35.0,0.0,33.0,33.0,19.0,16.0,13.0,21.0,10.0,0.0,15.0,7.0,22.0,68.0,53.0,NaN,NaN,30.0,30.0,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,NaN,0.0,20.0,NaN,0.0,0.0,0.0,0.0,153.0

In [9]:
df_consumption.isnull().sum()

Control Number        0
Account Name       2154
District           2445
Street             2154
Connection Type    2161
                   ...
2025_JAN           2173
2025_FEB           2170
2025_MAR           2168
2025_APR           2166
2025_MAY           2162
Length: 61, dtype: int64

### Disconnected consumers

In [25]:
df_disconnected = df_consumption[df_consumption["Connection Status"] == "Disconnected"]
df_disconnected.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
1,121.0,"Almodal, Maricel",District 2,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,500001.0,"Encinares, Roberto",District 4,Esparrago Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,500006.0,"Dejucos, Mercy",District 4,Esparrago Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,500007.0,"Cabiles, Nita",District 4,Esparrago Street,Residential,Disconnected,0.0,8.0,8.0,6.0,26.0,13.0,14.0,0.0,5.0,10.0,6.0,7.0,11.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,12.0,20.0,3.0,107.0,106.0,26.0,10.0,7.0,20.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,500012.0,"Dejucos, Lony",District 4,Alicante Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
print("="*20, "Printing df_disconnected.describe()", "="*20)
df_disconnected.describe()

==================== Printing df_disconnected.describe() ====================

,Control Number,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
count,472.000000,472.000000,348.000000,349.000000,353.000000,355.000000,355.000000,355.000000,354.000000,354.000000,356.000000,415.000000,415.000000,415.000000,348.000000,435.000000,436.000000,436.000000,438.000000,438.000000,445.000000,445.000000,440.000000,440.000000,451.000000,454.000000,454.000000,454.000000,454.000000,453.000000,455.000000,455.000000,455.000000,456.000000,457.000000,459.000000,459.000000,455.000000,455.000000,465.000000,465.000000,465.000000,467.000000,467.000000,467.000000,466.000000,468.000000,468.000000,469.000000,469.000000,469.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000
mean,499880.976695,0.054025,5.642241,8.512894,3.606232,13.539437,16.308451,8.904225,5.789548,6.334746,8.398876,4.848193,5.171084,5.168675,5.642241,5.082759,5.574541,4.121560,5.520548,0.441781,5.235955,0.405618,11.652841,11.555682,6.179601,5.610132,5.098018,4.061674,4.649780,0.039735,4.149451,6.101099,4.741758,5.429825,8.861050,4.600218,5.852941,7.509341,7.418132,4.516129,4.347312,3.983871,4.088865,3.501071,3.510707,3.253219,3.092949,3.477564,1.660981,1.939232,1.940299,3.559322,1.647246,1.226695,0.971398,0.054025,0.054025
std,23057.990497,1.064653,19.412384,22.478930,12.826892,35.666097,176.819396,22.840409,16.253531,16.986712,24.099755,16.541080,15.203360,13.749677,19.412384,16.096270,22.354939,12.464391,17.610249,4.499877,17.084694,2.294743,39.920152,39.840610,24.184865,17.325095,17.951116,12.118462,15.136962,0.845714,11.897075,17.378898,13.808309,16.147143,29.960626,16.402344,27.139653,29.381717,29.256490,18.891457,20.915865,18.827434,21.002788,16.110286,20.615291,15.987335,25.547630,27.460991,8.862626,11.153218,10.936181,34.212923,17.436906,11.507982,11.203423,1.064653,1.064653
min,121.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,500545.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,500900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,501283.000000,0.000000,0.000000,4.000000,0.000000,4.000000,3.000000,3.250000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,502134.000000,23.000000,156.000000,201.000000,111.000000,296.000000,3321.000000,167.000000,137.000000,173.000000,237.000000,188.000000,156.000000,88.000000,156.000000,138.000000,353.000000,99.000000,204.000000,73.000000,186.000000,22.000000,524.000000,524.000000,388.000000,170.000000,214.000000,127.000000,162.000000,18.000000,103.000000,146.000000,143.000000,171.000000,402.000000,150.000000,394.000000,330.000000,329.000000,251.000000,285.000000,240.000000,352.000000,274.000000,340.000000,224.000000,495.000000,464.000000,132.000000,130.000000,123.000000,540.000000,365.000000,226.000000,223.000000,23.000000,23.000000

In [27]:
print("="*20, "Printing number of nulls in df_disconnected", "="*20)
df_disconnected.isnull().sum()

==================== Printing number of nulls in df_disconnected ====================

Control Number      0
Account Name       23
District           91
Street             23
Connection Type    46
                   ..
2025_FEB            0
2025_MAR            0
2025_APR            0
2025_MAY            0
2025_SEP            0
Length: 62, dtype: int64

Based on the number of nulls, there are 23 records whose account name is missing.

In [28]:
# ========== CHECKING THE RECORDS WITH MISSING ACCOUNT NAMES =========
df_disconnected[df_disconnected["Account Name"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
236,500234.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
290,500288.0,NaN,NaN,NaN,NaN,Disconnected,0.0,14.0,0.0,0.0,27.0,13.0,4.0,4.0,5.0,7.0,3.0,5.0,5.0,14.0,18.0,9.0,0.0,4.0,0.0,16.0,0.0,13.0,12.0,2.0,25.0,27.0,16.0,21.0,0.0,14.0,25.0,15.0,25.0,36.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
312,500310.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433,500431.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
470,500468.0,NaN,NaN,NaN,NaN,Disconnected,0.0,9.0,10.0,24.0,29.0,15.0,14.0,9.0,13.0,29.0,15.0,27.0,0.0,9.0,40.0,10.0,72.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,0.0,5.0,5.0,1.0,2.0,3.0,1.0,3.0,4.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530,500528.0,NaN,NaN,NaN,NaN,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
685,500683.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
714,500712.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
726,500724.0,NaN,NaN,NaN,NaN,Disconnected,0.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
804,500801.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
888,500885.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
913,500910.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
936,500933.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,34.0,22.0,28.0,14.0,20.0,12.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
960,500957.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,3.0,5.0,8.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,500994.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1006,501002.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,19.0,16.0,48.0,0.0,0.0,8.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1019,501015.0,NaN,NaN,NaN,NaN,Disconnected,0.0,32.0,0.0,0.0,55.0,27.0,18.0,14.0,18.0,22.0,18.0,17.0,19.0,32.0,7.0,10.0,9.0,12.0,0.0,10.0,0.0,24.0,23.0,11.0,10.0,14.0,7.0,11.0,0.0,13.0,19.0,9.0,18.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1020,501016.0,NaN,NaN,NaN,NaN,Disconnected,0.0,30.0,0.0,0.0,95.0,47.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,30.0,1.0,5.0,4.0,6.0,0.0,7.0,0.0,8.0,8.0,2.0,1.0,2.0,0.0,0.0,0.0,1.0,13.0,7.0,5.0,12.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1057,501053.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1119,501114.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1547,501542.0,NaN,NaN,NaN,NaN,Disconnected,0.0,0.0,41.0,19.0,43.0,21.0,35.0,20.0,32.0,50.0,29.0,29.0,25.0,0.0,8.0,10.0,8.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1936,501930.0,NaN,NaN,NaN,NaN,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,13.0,10.0,1.0,12.0,0.0,14.0,11.0,9.0,16.0,28.0,5.0,13.0,11.0,11.0,6.0,13.0,7.0,9.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1970,501964.0,NaN,NaN,NaN,NaN,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,15.0,16.0,11.0,11.0,9.0,5.0,5.0,8.0,10.0,6.0,7.0,5.0,3.0,1.0,0.0,4.0,4.0,4.0,4.0,0.0,0.0,0.0

### Active consumers

In [29]:
df_active = df_consumption[df_consumption["Connection Status"] == "Active"]
df_active.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
4,500002.0,"Pareja, Myrna",District 4,Esparrago Street,Residential,Active,153.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,5.0,18.0,10.0,0.0,35.0,0.0,33.0,33.0,19.0,16.0,13.0,21.0,10.0,0.0,15.0,7.0,22.0,68.0,53.0,13.0,20.0,30.0,30.0,18.0,9.0,0.0,7.0,18.0,18.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,153.0,153.0
5,500003.0,"Bagobe, Penelope",District 4,Esparrago Street,Residential,Active,25.0,9.0,7.0,11.0,36.0,18.0,16.0,11.0,1.0,2.0,4.0,0.0,35.0,9.0,122.0,42.0,20.0,37.0,24.0,26.0,0.0,10.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0,46.0,65.0,0.0,103.0,103.0,24.0,12.0,10.0,14.0,6.0,13.0,10.0,10.0,10.0,5.0,20.0,24.0,20.0,20.0,22.0,21.0,25.0,25.0
6,500004.0,"Cerillo, Lea",District 4,Esparrago Street,Residential,Active,39.0,26.0,14.0,23.0,40.0,20.0,127.0,23.0,82.0,0.0,0.0,24.0,36.0,26.0,20.0,22.0,26.0,13.0,23.0,27.0,0.0,44.0,44.0,19.0,25.0,18.0,25.0,11.0,0.0,22.0,25.0,17.0,23.0,53.0,16.0,27.0,30.0,30.0,21.0,13.0,25.0,18.0,14.0,11.0,13.0,17.0,23.0,33.0,30.0,40.0,31.0,36.0,35.0,45.0,39.0,39.0
7,500005.0,"Bartolata, Ruel",District 4,Esparrago Street,Residential,Active,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,4.0,4.0,1.0,2.0,3.0,0.0,4.0,3.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,7.0,0.0,8.0,13.0,12.0,11.0,24.0,19.0,22.0,19.0,10.0,14.0,21.0,13.0,13.0
10,500008.0,"Genova, Erlinda",District 2,Alicante Street,Residential,Active,23.0,0.0,9.0,11.0,7.0,3.0,20.0,13.0,9.0,12.0,9.0,19.0,6.0,0.0,16.0,18.0,12.0,23.0,0.0,12.0,0.0,33.0,33.0,17.0,14.0,19.0,19.0,9.0,0.0,9.0,13.0,19.0,18.0,29.0,15.0,15.0,19.0,18.0,11.0,12.0,10.0,19.0,13.0,11.0,12.0,15.0,13.0,11.0,16.0,13.0,18.0,15.0,11.0,0.0,23.0,23.0

In [30]:
print("="*20, "Printing df_active.describe()", "="*20)
df_active.describe()

==================== Printing df_active.describe() ====================

,Control Number,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
count,1.688000e+03,1688.000000,1199.000000,1203.000000,1242.000000,1253.000000,1253.000000,1255.000000,1254.000000,1256.000000,1260.000000,1268.000000,1269.000000,1269.000000,1199.000000,1415.000000,1430.000000,1434.000000,1451.000000,1452.000000,1471.000000,1471.000000,1428.000000,1428.000000,1513.000000,1536.000000,1544.000000,1544.000000,1548.000000,1544.000000,1548.000000,1548.000000,1552.000000,1556.000000,1572.000000,1581.000000,1595.000000,1565.000000,1565.000000,1632.000000,1631.000000,1630.000000,1642.000000,1645.000000,1645.000000,1644.000000,1655.000000,1659.000000,1666.000000,1670.000000,1670.000000,1677.000000,1680.000000,1682.000000,1684.000000,1688.000000,1688.000000
mean,5.064556e+05,20.754443,11.222269,22.027431,10.536232,40.428970,22.118516,23.572908,17.349681,17.523089,23.917063,14.904968,18.602443,18.147754,11.222269,19.337102,19.391259,17.399233,22.316678,2.789945,23.240993,3.893610,40.265406,39.848214,19.196960,20.797201,19.351684,17.412565,17.814276,1.035622,17.442183,22.549096,19.989369,23.103149,41.061387,17.597090,22.482132,32.850000,32.406230,17.597426,17.855303,18.679141,22.427832,20.518541,16.631003,19.605231,19.504230,19.935805,21.033914,18.887126,22.620659,19.054264,18.858036,21.708680,23.002672,20.754443,20.754443
std,1.548737e+05,29.411819,23.209443,32.546806,18.808053,62.586886,68.168130,32.001945,36.785968,22.080662,31.464550,18.907468,21.694460,25.085085,23.209443,28.515365,27.101271,27.157615,32.081144,13.585499,31.399557,13.456395,51.109967,51.032226,26.094954,28.963260,26.487675,39.626204,31.014143,17.040325,23.120180,28.923140,27.818562,29.786202,48.789251,20.973806,29.860931,64.739582,64.690855,24.639616,24.456959,28.664993,28.301612,28.213690,23.359321,25.573481,21.885053,23.874602,26.047402,23.575522,29.492770,27.402099,26.544549,27.464571,30.465338,29.411819,29.411819
min,5.000020e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.005415e+05,7.000000,0.000000,1.500000,0.000000,3.000000,1.000000,4.000000,3.000000,3.000000,5.000000,3.750000,5.000000,4.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,7.000000,7.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,3.000000,5.000000,4.000000,5.000000,11.000000,4.000000,5.000000,9.000000,9.000000,4.000000,4.000000,5.000000,7.000000,6.000000,5.000000,7.000000,7.000000,7.000000,7.000000,7.000000,8.000000,6.000000,6.000000,8.000000,9.000000,7.000000,7.000000
50%,5.011785e+05,15.000000,0.000000,13.000000,0.000000,27.000000,13.000000,16.000000,11.000000,13.000000,17.000000,11.000000,14.000000,13.000000,0.000000,13.000000,13.000000,11.000000,15.000000,0.000000,16.000000,0.000000,29.000000,29.000000,13.000000,14.000000,13.000000,10.000000,11.000000,0.000000,12.000000,16.000000,13.000000,16.000000,30.000000,13.000000,17.000000,22.000000,21.000000,12.000000,13.000000,13.000000,18.000000,15.000000,12.000000,14.000000,15.000000,15.000000,15.000000,14.000000,17.000000,13.000000,13.000000,16.000000,18.000000,15.000000,15.000000
75%,5.016932e+05,25.000000,15.000000,30.000000,15.000000,52.000000,26.000000,30.000000,22.000000,23.000000,31.000000,20.000000,24.000000,24.000000,15.000000,25.000000,26.000000,23.000000,29.000000,0.000000,31.000000,0.000000,53.250000,53.000000,27.000000,28.000000,27.000000,21.000000,22.000000,0.000000,22.000000,30.000000,25.000000,30.000000,54.000000,23.000000,29.000000,39.000000,38.000000,23.000000,23.000000,23.000000,29.750000,26.000000,21.000000,25.000000,25.000000,25.000000,26.000000,23.000000,28.000000,23.000000,23.000000,26.000000,29.000000,25.000000,25.000000
max,5.002014e+06,525.000000,296.000000,426.000000,228.000000,1140.000000,2157.000000,367.000000,983.000000,250.000000,497.000000,291.000000,266.000000,447.000000,296.000000,369.000000,366.000000,400.000000,340.000000,241.000000,410.000000,258.000000,694.000000,693.000000,307.000000,326.000000,297.000000,1027.000000,614.000000,444.000000,252.000000,322.000000,360.000000,412.000000,674.000000,248.000000,514.000000,1509.000000,1508.000000,428.000000,362.000000,502.000000,491.000000,466.000000,478.000000,376.000000,238.000000,303.000000,429.000000,333.000000,499.000000,504.000000,454.000000,315.000000,686.000000,525.000000,525.000000

In [31]:
print("="*20, "Printing number of nulls in df_active", "="*20)
df_active.isnull().sum()

==================== Printing number of nulls in df_active ====================

Control Number       0
Account Name        78
District           347
Street              78
Connection Type    178
                  ...
2025_FEB             8
2025_MAR             6
2025_APR             4
2025_MAY             0
2025_SEP             0
Length: 62, dtype: int64

In [32]:
# ========== CHECKING THE RECORDS WITH MISSING ACCOUNT NAMES =========
df_active[df_active["Account Name"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
111,500109.0,NaN,NaN,NaN,NaN,Active,45.0,0.0,59.0,0.0,80.0,40.0,44.0,45.0,38.0,15.0,10.0,11.0,12.0,0.0,27.0,26.0,41.0,23.0,0.0,33.0,11.0,49.0,49.0,26.0,26.0,13.0,3.0,6.0,0.0,17.0,23.0,16.0,32.0,62.0,15.0,34.0,18.0,18.0,18.0,17.0,17.0,24.0,33.0,81.0,17.0,16.0,30.0,18.0,16.0,13.0,18.0,17.0,33.0,38.0,45.0,45.0
127,500125.0,NaN,NaN,NaN,NaN,Active,10.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,10.0,9.0,5.0,6.0,7.0,0.0,10.0,8.0,0.0,0.0,0.0,0.0,62.0,19.0,19.0,11.0,10.0,13.0,16.0,22.0,0.0,19.0,21.0,8.0,12.0,23.0,7.0,9.0,22.0,21.0,3.0,8.0,14.0,15.0,12.0,16.0,10.0,10.0,11.0,12.0,12.0,10.0,11.0,11.0,16.0,28.0,10.0,10.0
129,500127.0,NaN,NaN,NaN,NaN,Active,24.0,14.0,13.0,19.0,22.0,11.0,8.0,5.0,6.0,6.0,8.0,8.0,6.0,14.0,3.0,2.0,1.0,13.0,0.0,6.0,0.0,37.0,37.0,16.0,22.0,27.0,17.0,15.0,0.0,9.0,20.0,11.0,22.0,44.0,12.0,10.0,21.0,20.0,14.0,8.0,9.0,8.0,15.0,9.0,18.0,24.0,22.0,23.0,0.0,22.0,17.0,18.0,22.0,22.0,24.0,24.0
134,500132.0,NaN,NaN,NaN,NaN,Active,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,31.0,20.0,32.0,0.0,35.0,0.0,93.0,92.0,42.0,0.0,2.0,12.0,2.0,0.0,1.0,4.0,6.0,5.0,21.0,10.0,12.0,15.0,15.0,13.0,9.0,8.0,0.0,17.0,10.0,23.0,24.0,20.0,15.0,10.0,14.0,11.0,12.0,14.0,22.0,20.0,20.0
167,500165.0,NaN,NaN,NaN,NaN,Active,34.0,18.0,17.0,21.0,41.0,21.0,22.0,21.0,22.0,28.0,17.0,20.0,21.0,18.0,16.0,21.0,23.0,32.0,0.0,25.0,0.0,57.0,57.0,33.0,40.0,36.0,20.0,27.0,0.0,21.0,47.0,30.0,39.0,60.0,27.0,39.0,58.0,58.0,30.0,30.0,35.0,57.0,31.0,24.0,31.0,23.0,44.0,30.0,28.0,36.0,26.0,31.0,38.0,35.0,34.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2077,502073.0,NaN,NaN,NaN,NaN,Active,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,10.0,10.0,10.0,10.0,6.0,9.0,10.0,8.0,10.0,7.0,8.0,9.0,7.0,7.0,11.0,6.0,6.0
2148,502144.0,NaN,NaN,NaN,NaN,Active,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,9.0,11.0,16.0,12.0,32.0,38.0,37.0,37.0
2153,502149.0,NaN,NaN,NaN,NaN,Active,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,14.0,12.0,12.0,22.0,19.0,5.0,5.0
2159,502155.0,NaN,NaN,NaN,NaN,Active,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,18.0,15.0,11.0,11.0
2166,502162.0,NaN,NaN,NaN,NaN,Active,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,36.0,29.0,29.0

Based on the number of nulls, there are 78 records whose account name is missing.

### Temporarily closed consumers

In [33]:
df_temp_closed = df_consumption[df_consumption["Connection Status"] == "Temporarily Closed"]
df_temp_closed.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
144,500142.0,"Leynes, Angelo",District 3,Letada Street,Residential,Temporarily Closed,0.0,0.0,5.0,0.0,63.0,31.0,41.0,15.0,12.0,41.0,16.0,12.0,14.0,0.0,10.0,10.0,20.0,12.0,0.0,15.0,0.0,21.0,20.0,23.0,8.0,6.0,0.0,0.0,0.0,0.0,36.0,9.0,0.0,20.0,0.0,0.0,0.0,0.0,1.0,2.0,8.0,6.0,28.0,8.0,6.0,8.0,2.0,12.0,25.0,2.0,10.0,5.0,0.0,30.0,0.0,0.0
274,500272.0,"Barrun, Jesus",District 2,Jones Street,Residential,Temporarily Closed,0.0,0.0,17.0,12.0,21.0,11.0,12.0,13.0,10.0,12.0,8.0,12.0,12.0,0.0,14.0,7.0,4.0,12.0,0.0,11.0,0.0,23.0,23.0,16.0,16.0,23.0,20.0,12.0,0.0,5.0,12.0,11.0,17.0,30.0,40.0,0.0,7.0,7.0,0.0,NaN,12.0,13.0,11.0,0.0,22.0,19.0,15.0,13.0,13.0,19.0,19.0,0.0,15.0,8.0,0.0,0.0
330,500328.0,"Arcenas, Leny",District 1,Bailon Street,Commercial,Temporarily Closed,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,83.0,9.0,0.0,0.0,0.0,0.0,48.0,61.0,30.0,63.0,0.0,23.0,0.0,42.0,42.0,46.0,0.0,0.0,26.0,44.0,0.0,27.0,9.0,35.0,99.0,146.0,70.0,109.0,62.0,62.0,20.0,12.0,70.0,0.0,0.0,0.0,84.0,71.0,77.0,56.0,78.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
952,500949.0,"Almoete, Babylyn",District 2,Jones Street,Residential,Temporarily Closed,0.0,33.0,21.0,30.0,55.0,27.0,32.0,28.0,33.0,64.0,24.0,42.0,24.0,33.0,25.0,42.0,57.0,69.0,0.0,63.0,0.0,185.0,185.0,0.0,0.0,8.0,10.0,10.0,0.0,8.0,10.0,9.0,11.0,8.0,9.0,0.0,1888.0,1888.0,0.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1200,501195.0,"Bartolay, Dina",District 2,Jones Street,Residential,Temporarily Closed,0.0,10.0,10.0,14.0,23.0,11.0,12.0,8.0,9.0,11.0,9.0,9.0,8.0,10.0,12.0,9.0,11.0,17.0,0.0,14.0,0.0,30.0,29.0,11.0,14.0,18.0,6.0,5.0,0.0,8.0,16.0,16.0,17.0,24.0,13.0,18.0,19.0,18.0,6.0,12.0,10.0,15.0,10.0,12.0,12.0,9.0,7.0,8.0,6.0,3.0,6.0,6.0,6.0,14.0,0.0,0.0

In [34]:
print("="*20, "Printing df_temp_closed.describe()", "="*20)
df_temp_closed.describe()

==================== Printing df_temp_closed.describe() ====================

,Control Number,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
count,6.00000,6.0,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.0,6.000000,6.0,6.000000,6.000000,6.00000,6.000000,6.000000,6.000000,6.000000,6.0,6.000000,6.000000,6.000000,6.0000,6.000000,6.000000,6.000000,6.000000,6.00000,6.000000,5.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.0,6.0
mean,500754.00000,0.0,7.166667,9.000000,9.333333,29.000000,14.333333,18.166667,10.666667,24.833333,23.333333,9.500000,12.500000,17.833333,7.166667,35.333333,21.500000,20.333333,58.833333,0.0,48.666667,0.0,83.833333,83.333333,16.00000,6.333333,9.166667,25.833333,23.666667,0.0,19.000000,44.166667,22.000000,39.0000,73.500000,39.166667,42.500000,348.333333,348.00000,19.166667,16.600000,34.833333,7.333333,8.166667,3.333333,20.666667,17.833333,16.833333,14.833333,20.333333,4.000000,5.833333,1.833333,3.500000,8.666667,0.0,0.0
std,600.38421,0.0,13.272779,8.602325,11.977757,24.746717,12.127105,15.210742,10.576704,30.354022,23.938811,9.332738,15.462859,17.162945,13.272779,36.020365,24.254896,21.001587,64.712956,0.0,60.638821,0.0,85.433990,85.432234,17.23949,7.420692,9.474527,34.225234,27.875916,0.0,24.787093,68.259554,17.686153,43.5293,85.101704,40.385228,59.584394,755.483598,755.63298,34.574075,17.487138,39.569770,6.439462,10.998485,5.316641,32.116455,26.977151,30.022769,20.941983,29.776949,7.456541,7.652886,2.857738,6.123724,11.910779,0.0,0.0
min,500142.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,12.000000,0.0,11.000000,0.0,21.000000,20.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,9.000000,9.000000,0.0000,8.000000,0.000000,0.000000,0.000000,0.00000,0.000000,2.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,500286.00000,0.0,0.000000,2.000000,0.000000,14.250000,7.250000,12.000000,2.000000,9.250000,9.500000,2.000000,2.250000,9.000000,0.000000,12.500000,7.500000,5.750000,13.250000,0.0,14.250000,0.0,24.750000,24.500000,2.75000,0.000000,1.500000,7.000000,6.250000,0.0,5.750000,10.500000,9.500000,12.5000,21.000000,10.000000,0.000000,10.000000,9.75000,0.250000,10.000000,10.000000,1.500000,0.000000,0.000000,1.500000,2.000000,0.500000,2.000000,1.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
50%,500638.50000,0.0,0.000000,7.500000,6.000000,22.000000,11.000000,12.000000,10.500000,11.000000,11.500000,8.500000,10.500000,13.000000,0.000000,19.500000,9.500000,15.500000,40.000000,0.0,19.000000,0.0,36.000000,35.500000,13.50000,4.000000,7.000000,15.000000,11.000000,0.0,8.000000,14.000000,13.500000,17.0000,27.000000,26.500000,9.000000,40.500000,40.00000,3.500000,12.000000,11.000000,8.000000,5.000000,0.000000,9.000000,8.500000,4.500000,10.000000,9.500000,1.000000,3.000000,0.000000,0.000000,4.000000,0.0,0.0
75%,501133.50000,0.0,7.500000,15.250000,13.500000,47.000000,23.000000,27.000000,14.500000,27.750000,33.750000,14.250000,12.000000,21.500000,7.500000,42.250000,34.000000,27.500000,67.500000,0.0,53.000000,0.0,149.250000,149.250000,21.25000,12.500000,15.500000,24.500000,36.000000,0.0,22.250000,31.000000,30.250000,71.7500,117.000000,62.500000,86.250000,101.000000,100.25000,16.500000,12.000000,55.500000,12.250000,10.750000,6.000000,19.500000,16.500000,13.000000,12.750000,22.000000,2.750000,9.000000,3.750000,4.500000,12.500000,0.0,0.0
max,501638.00000,0.0,33.000000,21.000000,30.000000,63.000000,31.000000,41.000000,28.000000,83.000000,64.000000,24.000000,42.000000,49.000000,33.000000,103.000000,61.000000,57.000000,180.000000,0.0,166.000000,0.0,202.000000,201.000000,46.00000,16.000000,23.000000,93.000000,71.000000,0.0,66.000000,182.000000,52.000000,99.0000,213.000000,103.000000,128.000000,1888.000000,1888.00000,88.000000,47.000000,99.000000,15.000000,28.000000,12.000000,84.000000,71.000000,77.000000,56.000000,78.000000,19.000000,19.000000,6.000000,15.000000,30.000000,0.0,0.0

In [35]:
print("="*20, "Printing number of nulls in df_temp_closed", "="*20)
df_temp_closed.isnull().sum()

==================== Printing number of nulls in df_temp_closed ====================

Control Number     0
Account Name       0
District           0
Street             0
Connection Type    0
                  ..
2025_FEB           0
2025_MAR           0
2025_APR           0
2025_MAY           0
2025_SEP           0
Length: 62, dtype: int64

### Unknown consumers

In [36]:
df_unknown = df_consumption[df_consumption["Connection Status"] == "Unknown"]
df_unknown.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
0,0.0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50964.0,"Esparraguerra, Irish",District 2,Fabmar Street,Residential,Unknown,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,12.0,12.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,501109.0,"Almocera, Ricky",Calipat-an,Puro,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,501359.0,"Almodal, Maricel",District 2,Esparrago Street,Residential,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,15.0,12.0,9.0,0.0,67.0,0.0,0.0,22.0,31.0,72.0,0.0,149.0,149.0,77.0,56.0,58.0,75.0,54.0,0.0,41.0,19.0,20.0,148.0,216.0,7.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,501381.0,"Gaurano, Clutario",Calipat-an,Puro,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
print("="*20, "Printing df_unknown.describe()", "="*20)
df_unknown.describe()

==================== Printing df_unknown.describe() ====================

,Control Number,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
count,1.300000e+01,13.000000,4.00,4.0,4.0,4.0,4.00,4.0,4.0,4.0,4.000000,4.00000,4.000000,4.000000,4.00,4.00,4.0,4.0,4.0,4.00,4.0,4.0,4.00,4.00,4.00,4.0,4.0,4.00,4.0,4.0,4.00,5.000000,5.000000,4.000000,5.000000,7.000000,6.000000,3.0,3.0,3.0,3.0,3.0,5.000000,5.00000,5.000000,2.000000,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,7.761788e+05,3.538462,19.75,7.0,8.5,18.5,9.25,15.0,7.0,9.0,11.250000,16.00000,13.250000,12.000000,19.75,16.75,0.0,0.0,5.5,7.75,18.0,0.0,37.25,37.25,19.25,14.0,14.5,18.75,13.5,0.0,10.25,3.800000,4.000000,38.750000,43.200000,1.000000,8.833333,0.0,0.0,0.0,0.0,0.0,24.800000,12.00000,2.400000,3.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.285121e+06,11.080128,39.50,14.0,17.0,37.0,18.50,30.0,14.0,18.0,14.361407,23.10844,19.345542,18.493242,39.50,33.50,0.0,0.0,11.0,15.50,36.0,0.0,74.50,74.50,38.50,28.0,29.0,37.50,27.0,0.0,20.50,8.497058,8.944272,72.908047,96.598137,2.645751,16.129683,0.0,0.0,0.0,0.0,0.0,46.537082,20.78461,5.366563,4.242641,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,0.000000,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.013590e+05,0.000000,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.000000,1.500000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.020140e+05,0.000000,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,7.500000,7.50000,6.000000,4.500000,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,3.500000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.000000,3.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,5.040040e+05,0.000000,19.75,7.0,8.5,18.5,9.25,15.0,7.0,9.0,18.750000,23.50000,19.250000,16.500000,19.75,16.75,0.0,0.0,5.5,7.75,18.0,0.0,37.25,37.25,19.25,14.0,14.5,18.75,13.5,0.0,10.25,0.000000,0.000000,42.250000,0.000000,0.000000,9.750000,0.0,0.0,0.0,0.0,0.0,17.000000,12.00000,0.000000,4.500000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,5.012014e+06,40.000000,79.00,28.0,34.0,74.0,37.00,60.0,28.0,36.0,30.000000,49.00000,41.000000,39.000000,79.00,67.00,0.0,0.0,22.0,31.00,72.0,0.0,149.00,149.00,77.00,56.0,58.0,75.00,54.0,0.0,41.00,19.000000,20.000000,148.000000,216.000000,7.000000,40.000000,0.0,0.0,0.0,0.0,0.0,107.000000,48.00000,12.000000,6.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
print("="*20, "Printing number of nulls in df_unknown", "="*20)
df_unknown.isnull().sum()

==================== Printing number of nulls in df_unknown ====================

Control Number      0
Account Name        1
District            9
Street              1
Connection Type    11
                   ..
2025_FEB           13
2025_MAR           13
2025_APR           13
2025_MAY           13
2025_SEP           13
Length: 62, dtype: int64

In [39]:
# ========== CHECKING THE RECORDS WITH MISSING ACCOUNT NAMES =========
df_unknown[df_unknown["Account Name"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
2175,504008.0,NaN,NaN,NaN,NaN,Unknown,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Check missing districts

In [ ]:
df_consumption = pd.read_csv("../../../dataset/clean/production/tabular/consumption_consolidated.csv")
df_consumption[df_consumption["District"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY,2025_SEP
0,0.0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,500016.0,"Gutierrez, Robert",NaN,Moyot Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,20.0,27.0,15.0,22.0,0.0,26.0,0.0,34.0,33.0,17.0,14.0,7.0,16.0,31.0,0.0,21.0,23.0,28.0,26.0,39.0,20.0,23.0,58.0,58.0,0.0,16.0,27.0,22.0,25.0,19.0,21.0,18.0,16.0,17.0,13.0,11.0,12.0,11.0,18.0,19.0,0.0,0.0
19,500017.0,"Almosara, Elsie",NaN,Moyot Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,500018.0,"Quijano, Asteria",NaN,Moyot Street,Residential,Active,0.0,14.0,12.0,0.0,92.0,46.0,26.0,16.0,15.0,18.0,10.0,20.0,20.0,14.0,22.0,13.0,24.0,11.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,240.0,34.0,34.0,0.0,43.0,44.0,54.0,36.0,93.0,37.0,43.0,50.0,50.0,30.0,20.0,15.0,35.0,45.0,21.0,45.0,52.0,50.0,43.0,47.0,58.0,137.0,98.0,15.0,12.0,0.0,0.0
39,500037.0,"Espera, Nory",NaN,Moyot Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173,502556.0,"Gabad,Jason",NaN,Letada Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,504004.0,"Altarejos, Ciceron",NaN,NHA Duplex,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2175,504008.0,NaN,NaN,NaN,NaN,Unknown,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2176,507076.0,"Villanueva, Jessica",NaN,Jones Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2179,5012014.0,"Serra, Sheena",NaN,Alicante Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_consumption["District"].isnull().sum()

np.int64(447)

### Next steps

Following the data exploration, the following must be done afterwards:

- Fill the missing account names in the consumer records using the `consolidated.csv` dataset
- Fill the missing districts, streets, and connection types
- Cross-reference the 0 consumption values between nonzero values
- Correct those 0 values based on the cross reference results